name: codequest_pipes
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec spec
      - run: bash push.sh